import React from 'react'

const LogIn = () => {
  return (
    <div className="w-60 h-[100px] relative">
    <div className="w-60 h-[100px] left-0 top-0 absolute bg-white rounded-[15px] border border-stone-700" />
    <div className="w-[144.42px] h-[51.92px] left-[49px] top-[24px] absolute text-center text-stone-700 text-[40px] font-medium font-['Poppins']">Log In</div>
</div>
  )
}

export default LogIn